{% set version = "7.0.0" %}

package:
    name: pyferret
    version: {{ version }}

source:
    fn: pyferret-{{ version }}.tar.gz
    url: https://github.com/NOAA-PMEL/PyFerret/archive/v{{ version }}-final.tar.gz
    sha256: b6595198a276109c83d987b153c456c3f146918ee783f22501ea634da4d17853
    patches:
        - site_specific.patch

build:
    number: 4
    skip: True  # [not (linux and py27)]

requirements:
    build:
        - python
        - numpy
        - netcdf-fortran 4.4.*
        - cairo
        - pango
        - gcc
    run:
        - python
        - numpy
        - netcdf-fortran 4.4.*
        - cairo
        - pango
        - pyqt
        - libgcc

test:
    imports:
        - pyferret
    commands:
        - conda inspect linkages -n _test pyferret  # [not win]

about:
    home: http://ferret.pmel.noaa.gov/Ferret
    license: MIT
    summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
    recipe-maintainers:
        - eugeneburger
        - karlmsmith
        - ocefpaf
