{% set version = "7.6.5" %}

package:
  name: pyferret
  version: {{ version }}

source:
  url: https://github.com/NOAA-PMEL/PyFerret/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1cc96a7b2ac87a2df3808d1c4d14604a2f5bad11f3c0d129b51b5f810c3102c7
  patches:
    - intel-mac-edit.diff  # [osx]
    - patch-linux-pango.diff  # [linux64]
    - patch-linux64-gnu-gfortran10.diff  # [linux64]

build:
  number: 4
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make

  host:
    - python
    - cairo
    - glib
    - libnetcdf
    - netcdf-fortran
    - numpy
    - pango
    - pixman

  run:
    - python
    - cairo
    - glib
    - libnetcdf
    - netcdf-fortran
    - numpy
    - pango
    - pixman
    - pyqt

test:
  imports:
    - pyferret

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: An Analysis Tool for Gridded and Non-Gridded Data.

  description: |
    The PyFerret program and Python module from NOAA/PMEL.
    See https://ferret.pmel.noaa.gov/Ferret/ for more information about Ferret and PyFerret.

    This repository is regularly synchronized with PyFerret repository at PMEL 
    (the pyferret branch of the ferret project in the subversion repository at PMEL) using git-svn.

  dev_url: https://github.com/NOAA-PMEL/PyFerret
  doc_url: https://ferret.pmel.noaa.gov/Ferret/

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmattsmith
    - ocefpaf
    - ngam
