{% set version = "7.4.2" %}

package:
  name: pyferret
  version: {{ version }}

source:
  url: https://github.com/NOAA-PMEL/PyFerret/archive/{{ version }}.tar.gz
  sha256: de5359f77e19d4b82e84b35b0092cdeab3eadf3166301187979c8cec45d4e55c

build:
  number: 0
  skip: True  # [win or py3k]

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - netcdf-fortran
    - cairo
    - pango
    - pixman
  run:
    - python
    - numpy
    - netcdf-fortran
    - cairo
    - pango
    - pixman
    - pyqt

test:
  imports:
    - pyferret
  commands:
    - conda inspect linkages -p $PREFIX pyferret  # [not win]
    - conda inspect objects -p $PREFIX pyferret  # [osx]

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
