{% set version = "7.6.5" %}

package:
  name: pyferret
  version: {{ version }}

source:
  url: https://github.com/NOAA-PMEL/PyFerret/archive/refs/tags/v{{ version }}-beta.tar.gz
  sha256: 965ad4b8f71adbb3d4d3ba9aa9f22ac485a7c0489f312c534afc190eebca0e59
  patches:
    - intel-mac-edit.diff  # [osx]
    - patch.diff  # [linux64]

build:
  number: 0
  number: 4
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    
  host:
    - python
    - cairo
    - glib
    - libnetcdf
    - netcdf-fortran
    - numpy
    - pango
    - pixman

  run:
    - python
    - cairo
    - glib
    - libnetcdf
    - netcdf-fortran
    - numpy
    - pango
    - pixman
    - pyqt

test:
  imports:
    - pyferret

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - josborne-noaa
    - karlmattsmith
    - ocefpaf
    - ngam
