{% set version = "7.6.3" %}

package:
  name: pyferret
  version: {{ version }}

source:
  url: https://github.com/NOAA-PMEL/PyFerret/archive/v{{ version }}.tar.gz
  sha256: f062c20bedf64713f57c3d45aaeb63eb9b4d3ba622e5c5e4a99e61fdf08d2224
  patches:
    - intel-mac.patch  # [osx]
    - patch.diff

build:
  number: 3
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - make
    
  host:
    - python
    - cairo
    - glib
    - libnetcdf
    - netcdf-fortran
    - numpy
    - pango
    - pixman

  run:
    - python
    - cairo
    - glib
    - libnetcdf
    - netcdf-fortran
    - numpy
    - pango
    - pixman
    - pyqt

test:
  imports:
    - pyferret

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - josborne-noaa
    - karlmattsmith
    - ocefpaf
    - ngam
