{% set version = "7.4" %}

package:
  name: pyferret
  version: {{ version }}

source:
  url: https://github.com/NOAA-PMEL/PyFerret/archive/v{{ version }}.tar.gz
  sha256: b3aceb99f35311f72bd33851b5ffa948f2df070d9d3bec347d7515632fd536c7
  patches:
    - linux-platform_specific.patch  # [linux]

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - python
    - numpy
    - netcdf-fortran 4.4.*
    - cairo 1.14.*
    - pango 1.42.*
    - pixman 0.34.*
    - gcc  # [not win]
  run:
    - python
    - numpy
    - netcdf-fortran 4.4.*
    - cairo 1.14.*
    - pango 1.42.*
    - pixman 0.34.*
    - pyqt 5.*
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - pyferret
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
