{% set version = "7.5.0" %}

package:
  name: pyferret
  version: {{ version }}

source:
  url: https://github.com/NOAA-PMEL/PyFerret/archive/v{{ version }}.tar.gz
  sha256: 5e18051e6e68374445a3bdd08fff278f50f03d94f32d6f7960afcd587266216b
  patches:
    - intel-mac.patch  # [osx]

build:
  number: 5
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
  host:
    - python
    - numpy
    - netcdf-fortran
    - libnetcdf
    - cairo
    - pango
    - pixman
  run:
    - python
    - numpy
    - netcdf-fortran
    - libnetcdf
    - cairo
    - pango
    - pixman
    - pyqt
    - sip

test:
  imports:
    - pyferret

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
