{% set version = "7.2.1" %}

package:
  name: pyferret
  version: {{ version }}

source:
  url: https://github.com/NOAA-PMEL/PyFerret/archive/v{{ version }}-final.tar.gz
  sha256: c285455d7efebf33d7cb55eb0480d18efa580e51b6bca082c150cdf0ea9aa6ab
  patches:
    - platform_specific.mk.x86_64-linux.patch
    - sp_dir.patch

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - python
    - numpy 1.9.*
    - netcdf-fortran 4.4.*
    - cairo 1.14.*
    - pango 1.40.*
    - pixman 0.34.*
    - scipy
    - pyshp
    - gcc  # [not win]
  run:
    - python
    - numpy >=1.8
    - netcdf-fortran 4.4.*
    - cairo 1.14.*
    - pango 1.40.*
    - pixman 0.34.*
    - scipy
    - pyshp
    - pyqt 5.6.*
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - pyferret
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://ferret.pmel.noaa.gov/Ferret
  license: MIT
  license_file: LICENSE
  summary: 'An Analysis Tool for Gridded and Non-Gridded Data.'

extra:
  recipe-maintainers:
    - eugeneburger
    - karlmsmith
    - ocefpaf
