travis:
  secure:
    BINSTAR_TOKEN: BH5jUFuo6KICHx24HzPwD5mLVIbb5xqp5AJ6SgcOA+pOwNy8QOqiHJ0UK+vJLtGVBxqQRf0oLkGlMzyDJBmzUGA0NqjDd7DcltZEJv6RqE/LJ9rMclADlz/+0j3R6hf7Oa8NSRBzk2NeoWRehXzKPwD0TOXJDGeB4rkX9uOnYxaAFb7omJwSpuPyNx2L4ocULipHTTDIdz4acIAgBTzcHGnaO7YFkhwytVEsuHGRYgEq5tmspOHDDGocefLy4rsXnzDMaMGVddqpMm71DLg55GM1MZXdqauj/uCb7NSqdD6bEiRq1lzsIJgzMIpVTWni4nwhwztbQKdpdUWLDqy+YjJZIUR1ErLYU89T3idtE+E0WNVUPIe/q49RJYzP6RDF58XCIHkDejfl3TD55/QLs7t1gaHs7MEQQLvnjgUh0rDwMEg1toXBnDXhzmRxTo03HyXsMTvkenvXJ8cYMJaPl9nlqdZ1Rvhh/TN8+ygjSLusI1W4VPr28OuWo5PfVbs5DZalO25yRPesJdkR35EiCF/AeOyesoyazVHV8SSF1XmwMpb9KyvNOBJZHCvVHro6svoO4OUNf95quMBuzo8VX0WdpUKN4h0kGtRPcA0J7AiCVV+1ZP1uci130uEEk5b7/XcpLNSJSfriXzoCno1PSeWEdtbr9+NcK74QIFA9kts=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
